In [6]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x - x.mean()
    
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.3970e-09, grad_fn=<MeanBackward0>)

### 5.4.2 带参数的层
使用内置函数来创建参数

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1142, -0.1476, -0.2874],
        [-1.0642,  0.3288, -3.1876],
        [-1.7374,  0.8510,  0.4982],
        [ 0.0342, -1.9960,  1.3330],
        [ 0.6684,  0.4495,  0.9044]], requires_grad=True)

In [ ]:
linear(torch.rand(2, 5)) # 一个形状为[2, 5]的输入

tensor([[0.0000, 0.6838, 0.0000],
        [0.0000, 0.5855, 0.0000]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2,  64))

tensor([[0.],
        [0.]])